### ISSUE TITLE
link to the paper?

### ISSUE THREAD

**Issue by joyZWL** [Weepingchestnut/SAVSR#1]
This paper is very excellent, can you put a link to the paper?

**Comment by Weepingchestnut** [comment]
Thank you for your attention! We are checking the final camera-ready version with the AAAI press editorial team. We will release a link to the paper as soon as the checking is complete.

**Comment by joyZWL** [comment]
> Thank you for your attention! We are checking the final camera-ready version with the AAAI press editorial team. We will release a link to the paper as soon as the checking is complete.

Hello, I heard that the AAAI checking has already completed,  can you please release your paper? I want to ask which baseline models are selected for comparison in your paper?

**Comment by Weepingchestnut** [comment]
I'm sorry to release our paper so late, please see the paper in [releases](https://github.com/Weepingchestnut/SAVSR/releases).
